SELECT current_database();

CREATE TABLE customers (
    customer_id TEXT PRIMARY KEY,
    customer_unique_id TEXT,
    customer_zip_code_prefix INT,
    customer_city TEXT,
    customer_state TEXT
);

CREATE TABLE orders (
    order_id TEXT PRIMARY KEY,
    customer_id TEXT,
    order_status TEXT,
    order_purchase_timestamp TIMESTAMP,
    order_approved_at TIMESTAMP,
    order_delivered_carrier_date TIMESTAMP,
    order_delivered_customer_date TIMESTAMP,
    order_estimated_delivery_date TIMESTAMP
);


CREATE TABLE order_items (
    order_id TEXT,
    order_item_id INT,
    product_id TEXT,
	seller_id TEXT,
	shipping_limit_date TEXT,
    price NUMERIC,
    freight_value NUMERIC
);

CREATE TABLE products (
    product_id TEXT,
    product_category_name TEXT,
    product_name_length INT,
    product_description_length INT,
    product_photos_qty INT,
    product_weight_g NUMERIC,
    product_length_cm NUMERIC,
    product_height_cm NUMERIC,
    product_width_cm NUMERIC
);

CREATE TABLE payments (
    order_id TEXT,
	payment_sequential INT,
    payment_type TEXT,
	payment_installments INT,
    payment_value NUMERIC
);


SELECT COUNT (*) FROM customers;
SELECT COUNT (*) FROM orders;
SELECT COUNT (*) FROM order_items;
SELECT COUNT (*) FROM products;
SELECT COUNT (*) FROM payments;


SELECT COUNT(*) 
FROM products
WHERE product_category_name IS NULL;


CREATE TABLE ecommerce_master AS
SELECT 
    o.order_id,
    o.customer_id,
    c.customer_unique_id,
    o.order_purchase_timestamp,
    
    oi.product_id,
    oi.price,
    oi.freight_value,
    
    p.product_category_name,
    
    pay.payment_type,
    pay.payment_value

FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
JOIN products p ON oi.product_id = p.product_id
JOIN payments pay ON o.order_id = pay.order_id;


SELECT 
    *,
    DATE_TRUNC('month', order_purchase_timestamp) AS order_month
FROM ecommerce_master;


SELECT 
    *,
    (price + freight_value) AS total_amount
FROM ecommerce_master;

CREATE TABLE ecommerce_final AS
SELECT 
    order_id,
    customer_unique_id,
    product_id,
    product_category_name,
    payment_type,
    
    DATE_TRUNC('month', order_purchase_timestamp) AS order_month,
    
    price,
    freight_value,
    (price + freight_value) AS total_amount

FROM ecommerce_master;


SELECT * FROM ecommerce_final;


==============================================

--BUSINESS ANALYSIS

==============================================

--1. Total Revenue
SELECT SUM(total_amount) AS total_revenue
FROM ecommerce_final;

-- Total Revenue = 42703


--2. Monthly Revenue Trend
SELECT 
	order_month,
	SUM(total_amount) AS monthly_revenue
FROM ecommerce_final
GROUP BY order_month
ORDER BY monthly_revenue;

-- Key Insight - Salees are increasing Month on Month.


--3. Top Customers
SELECT 
	customer_unique_id,
	SUM(total_amount) AS total_spent
FROM ecommerce_final
GROUP BY customer_unique_id
ORDER BY total_spent DESC
LIMIT 10;

-- Key Insight - Hiighest revenue from the top Customer is 13664.08


--4. Top Products
SELECT
	product_id,
	SUM(total_amount) AS revenue
FROM ecommerce_final
GROUP BY product_id
ORDER BY revenue DESC
LIMIT 10;

-- Key Insight - The highest revenue generated by top sold item is 72470


--5. Category Performance
SELECT
	product_category_name,
	SUM(total_amount) AS revenue
FROM ecommerce_final
GROUP BY product_category_name
ORDER BY revenue DESC;
 
-- Key Insight - Beleza_Saude, relogios_presentes,cama_mesa_banho are the top category revenue driver


--6. Payment method analysis
SELECT
	payment_type,
	SUM(total_amount) AS revenue
FROM ecommerce_final
GROUP BY payment_type
ORDER BY revenue DESC;

-- Key Insight - Customers prefer Credit card for paymennts over other payment methods


--7. Repeat vs New Customers
WITH customer_orders AS (
    SELECT 
        customer_unique_id,
        COUNT(DISTINCT order_id) AS order_count
    FROM ecommerce_final
    GROUP BY customer_unique_id
)

SELECT 
    CASE 
        WHEN order_count = 1 THEN 'New'
        ELSE 'Repeat'
    END AS customer_type,
    COUNT(*) AS customers
FROM customer_orders
GROUP BY customer_type;

-- Key Insight - Business is attracting more and more new customers


--8. Customer Segmentation
WITH customer_spending AS (
    SELECT 
        customer_unique_id,
        SUM(total_amount) AS total_spent
    FROM ecommerce_final
    GROUP BY customer_unique_id
)

SELECT 
    customer_unique_id,
    total_spent,
    CASE 
        WHEN total_spent > 1000 THEN 'High Value'
        WHEN total_spent > 500 THEN 'Medium Value'
        ELSE 'Low Value'
    END AS segment
FROM customer_spending;

-- Key Insight - Customers prefer spending low value  on the goods


--9. Pareto Analysis
WITH revenue_rank AS (
    SELECT 
        customer_unique_id,
        SUM(total_amount) AS revenue,
        SUM(SUM(total_amount)) OVER () AS total_revenue,
        SUM(SUM(total_amount)) OVER (ORDER BY SUM(total_amount) DESC) AS cumulative_revenue
    FROM ecommerce_final
    GROUP BY customer_unique_id
)
SELECT 
	*,
	(cumulative_revenue/total_revenue) * 100 AS cumulative_percentage
FROM revenue_rank;

